include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  plugins:
    - custom_lint

linter:
  rules:
    # Error rules
    always_use_package_imports: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    empty_statements: true
    hash_and_equals: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true

    # Style rules
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    camel_case_types: true
    empty_catches: true
    empty_constructor_bodies: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: false
    constant_identifier_names: false
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_generic_function_type_aliases: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_spread_collections: true
    recursive_getters: true
    slash_for_doc_comments: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true
    valid_regexps: true

    # Flutter specific rules
    use_build_context_synchronously: false
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_const_constructors_in_immutables: true
    sized_box_for_whitespace: true
    use_colored_box: true
    use_decorated_box: true
    use_full_hex_values_for_flutter_colors: true

    always_put_required_named_parameters_first: true
    avoid_print: true  # Use logging instead
    avoid_redundant_argument_values: true
    depend_on_referenced_packages: true
    eol_at_end_of_file: true
    package_api_docs: true  # Encourages documentation
    prefer_final_in_for_each: true
    prefer_final_locals: true
    require_trailing_commas: true  # Helps with git diffs
    sort_child_properties_last: true
    sort_pub_dependencies: true
    unnecessary_late: true
    use_string_buffers: true
#    flutter_style_todos: true