name: flutter_persian_calendar
description: >
  Flutter package for easy integration of Persian (Jalali) calendar widgets. 
  Customize appearance, filter dates, and simplify date selection.
repository: https://github.com/Amirnlz/flutter_persian_calendar
homepage: https://github.com/Amirnlz/flutter_persian_calendar

version: 0.0.3

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shamsi_date: ^1.0.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
