name: flutter_persian_calendar
description: >
  Flutter package for Persian (Jalali) calendar integration. 
  Customize appearance, filter dates, and simplify selection.
version: 0.0.1
repository: https://github.com/Amirnlz/flutter_persian_calendar
homepage: https://github.com/Amirnlz/flutter_persian_calendar

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shamsi_date: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
